# Generated by Django 3.2.23 on 2024-04-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(max_length=30)),
                ('rlastname', models.CharField(max_length=30)),
                ('remail', models.CharField(max_length=30)),
                ('rphone', models.IntegerField()),
                ('rperson', models.CharField(max_length=30)),
                ('rtable', models.CharField(max_length=30)),
                ('rdate', models.CharField(max_length=30)),
                ('rtime', models.CharField(max_length=30)),
                ('rcomment', models.CharField(max_length=50)),
            ],
        ),
    ]
